import * as balancing from 'src/game-engine/constants/balancing'
import * as cardText from 'src/game-engine/constants/cardText'
import type { CardBase, CardBaseId } from 'src/game-engine/types'
import { messages } from 'src/i18n'

export const CARD_BASES: Record<CardBaseId, CardBase> = {
  // Chaos --------------------------------------- /
  zombie: {
    id: 'zombie',
    name: messages.cards.zombie.name,
    faction: 'chaos',
    categories: ['Undead'],
    type: 'Character',
    attributes: balancing.ZOMBIE_ATTRIBUTES,
    text: cardText.ZOMBIE_TEXT,
  },
  burrick: {
    id: 'burrick',
    name: messages.cards.burrick.name,
    type: 'Character',
    categories: ['Beast'],
    faction: 'chaos',
    attributes: balancing.BURRICK_ATTRIBUTES,
    text: cardText.BURRICK_TEXT,
  },
  minesGuardian: {
    id: 'minesGuardian',
    name: messages.cards.minesGuardian.name,
    type: 'Character',
    categories: ['Undead'],
    faction: 'chaos',
    attributes: balancing.MINES_GUARDIAN_ATTRIBUTES,
    text: cardText.MINES_GUARDIAN_TEXT,
  },
  guardianStatue: {
    id: 'guardianStatue',
    name: messages.cards.guardianStatue.name,
    type: 'Character',
    categories: ['Elemental'],
    faction: 'chaos',
    attributes: balancing.GUARDIAN_STATUE_ATTRIBUTES,
    text: cardText.GUARDIAN_STATUE_TEXT,
  },
  haunt: {
    id: 'haunt',
    name: messages.cards.haunt.name,
    faction: 'chaos',
    categories: ['Undead', 'Hammerite'],
    type: 'Character',
    attributes: balancing.HAUNT_ATTRIBUTES,
    text: cardText.HAUNT_TEXT,
  },
  mysticsSoul: {
    id: 'mysticsSoul',
    name: messages.cards.mysticsSoul.name,
    type: 'Instant',
    isElite: true,
    categories: ['Artifact'],
    faction: 'chaos',
    attributes: balancing.MYSTICS_SOUL_ATTRIBUTES,
    text: cardText.MYSTICS_SOUL_TEXT,
  },
  bookOfAsh: {
    id: 'bookOfAsh',
    name: messages.cards.bookOfAsh.name,
    faction: 'chaos',
    categories: ['Necromancer', 'Artifact'],
    type: 'Instant',
    isElite: true,
    attributes: balancing.BOOK_OF_ASH_ATTRIBUTES,
    text: cardText.BOOK_OF_ASH_TEXT,
  },

  // Order --------------------------------------- /

  novice: {
    id: 'novice',
    name: messages.cards.novice.name,
    faction: 'order',
    categories: ['Hammerite'],
    type: 'Character',
    attributes: balancing.NOVICE_ATTRIBUTES,
    text: cardText.NOVICE_TEXT,
  },
  elevatedAcolyte: {
    id: 'elevatedAcolyte',
    name: messages.cards.elevatedAcolyte.name,
    faction: 'order',
    categories: ['Hammerite'],
    type: 'Character',
    attributes: balancing.ELEVATED_ACOLYTE_ATTRIBUTES,
    text: cardText.ELEVATED_ACOLYTE_TEXT,
  },
  templeGuard: {
    id: 'templeGuard',
    name: messages.cards.templeGuard.name,
    faction: 'order',
    categories: ['Hammerite'],
    type: 'Character',
    attributes: balancing.TEMPLE_GUARD_ATTRIBUTES,
    text: cardText.TEMPLE_GUARD_TEXT,
  },
  sachelman: {
    id: 'sachelman',
    name: messages.cards.sachelman.name,
    faction: 'order',
    categories: ['Hammerite', 'Brother'],
    type: 'Character',
    isElite: true,
    attributes: balancing.SACHELMAN_ATTRIBUTES,
    text: cardText.SACHELMAN_TEXT,
  },
  yoraSkull: {
    id: 'yoraSkull',
    name: messages.cards.yoraSkull.name,
    faction: 'order',
    categories: ['Hammerite', 'Artifact'],
    type: 'Instant',
    isElite: true,
    attributes: balancing.YORA_SKULL_ATTRIBUTES,
    text: cardText.YORA_SKULL_TEXT,
  },
  markander: {
    id: 'markander',
    name: messages.cards.markander.name,
    type: 'Character',
    categories: ['Hammerite', 'High', 'Priest'],
    faction: 'order',
    isElite: true,
    attributes: balancing.MARKANDER_ATTRIBUTES,
    text: cardText.MARKANDER_TEXT,
  },

  // Shadow --------------------------------------- /

  downwinder: {
    id: 'downwinder',
    name: messages.cards.downwinder.name,
    faction: 'shadow',
    categories: ['Thief'],
    type: 'Character',
    attributes: balancing.DOWNWINDER_ATTRIBUTES,
    text: cardText.DOWNWINDER_TEXT,
  },

  // Neutral --------------------------------------- /

  cook: {
    id: 'cook',
    name: messages.cards.cook.name,
    faction: 'neutral',
    categories: ['Household'],
    type: 'Character',
    attributes: balancing.COOK_ATTRIBUTES,
    text: cardText.COOK_TEXT,
  },
  speedPotion: {
    id: 'speedPotion',
    name: messages.cards.speedPotion.name,
    type: 'Instant',
    categories: ['Equipment'],
    faction: 'neutral',
    attributes: balancing.SPEED_POTION_ATTRIBUTES,
    text: cardText.SPEED_POTION_TEXT,
  },
  flashBomb: {
    id: 'flashBomb',
    name: messages.cards.flashBomb.name,
    type: 'Instant',
    categories: ['Equipment'],
    faction: 'neutral',
    attributes: balancing.FLASH_BOMB_ATTRIBUTES,
    text: cardText.FLASH_BOMB_TEXT,
  },
}
