export const bottomPlayerDeckCardId = 'bottomPlayerDeckCardId'
export const bottomPlayerDiscardCardId = 'bottomPlayerDiscardCardId'
export const bottomPlayerBoardCardId = 'bottomPlayerBoardCardId'
export const bottomPlayerHandCardId = 'bottomPlayerHandCardId'
export const topPlayerDeckCardId = 'topPlayerDeckCardId'
export const topPlayerDiscardCardId = 'topPlayerDiscardCardId'
export const topPlayerBoardCardId = 'topPlayerBoardCardId'
export const topPlayerHandCardId = 'topPlayerHandCardId'
